### ISSUE TITLE
Error: Cannot find module 'vuepress-theme-yubisaki/package.json'

### ISSUE THREAD

**Issue by farnetani** [Bloss/vuepress-theme-yubisaki-example#2]
```
Windows 10
$ node -v
v10.15.3
$ npm -v
6.9.0
```

When I run the command vuepress dev docs usually runs with a small error only in Tags.

But, when I try to build (vuepress build docs), I get the following error:

```
Error: Cannot find module 'vuepress-theme-yubisaki/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at normalizeThemePath (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\loadTheme.js:59:33)
    at resolveTheme (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\loadTheme.js:103:12)
    at loadTheme (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\loadTheme.js:36:17)
    at App.process (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\App.js:97:21)
    at build (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\index.js:20:13)
    at args (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\lib\util.js:35:12)
    at CAC.cli.command.option.option.option.option.option.option.option.action (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\lib\registerCoreCommands.js:59:25)
    at CAC.runMatchedCommand (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\cac\dist\index.js:787:38)
    at CAC.parse (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\cac\dist\index.js:707:18)
    at CLI (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\lib\util.js:23:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by farnetani** [comment]
I solved! I think the problem was related to having deleted the package.lock and yarn.lock.
