### ISSUE TITLE
Error: Cannot find module 'vue-property-decorator'

### ISSUE THREAD

**Issue by farnetani** [Bloss/vuepress-theme-yubisaki-example#3]
When I execute the command: `vuepress build docs` result in error bellow:

```
$ vuepress build docs
wait Extracting site metadata...
tip Apply local theme at U:\Arquivos\Web\Web\2019\farnetani-blog-yubisaki\docs\.vuepress\theme...
tip Apply theme local ...
warning Cannot read property 'Page' of undefined
tip Apply plugin container (i.e. "vuepress-plugin-container") ...
tip Apply plugin @vuepress/register-components (i.e. "@vuepress/plugin-register-components") ...
tip Apply plugin @vuepress/back-to-top (i.e. "@vuepress/plugin-back-to-top") ...
tip Apply plugin @vuepress/medium-zoom (i.e. "@vuepress/plugin-medium-zoom") ...
tip Apply plugin @vssue/vssue (i.e. "@vssue/vuepress-plugin-vssue") ...
tip Apply plugin @yubisaki/pagination (i.e. "@yubisaki/vuepress-plugin-pagination") ...
tip Apply plugin flowchart (i.e. "vuepress-plugin-flowchart") ...
tip Apply plugin @vuepress/pwa (i.e. "@vuepress/plugin-pwa") ...
tip Apply plugin @vuepress/search (i.e. "@vuepress/plugin-search") ...
tip Apply plugin @vuepress/google-analytics (i.e. "@vuepress/plugin-google-analytics") ...
[19:57:47] Compiling Client
[19:57:47] Compiling Server
[19:57:55] Compiled Server in 8s
[19:58:00] Compiled Client in 13s
wait Rendering static HTML...
Rendering page: /about/error Error rendering /about/: false
undefined
Error: Cannot find module 'vue-property-decorator'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at r (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-server-renderer\build.dev.js:9300:16)    at Object.<anonymous> (webpack:/external "vue-property-decorator":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (server-bundle.js:58845:40)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.module.exports.exports.__esModule (server-bundle.js:43701:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at server-bundle.js:118:18
    at Object.<anonymous> (server-bundle.js:121:10)
    at evaluateModule (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-server-renderer\build.dev.js:9303:21)
    at C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-server-renderer\build.dev.js:9361:18    at new Promise (<anonymous>)    at C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-server-renderer\build.dev.js:9353:14    at Object.renderToString (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\vue-server-renderer\build.dev.js:9529:9)    at Build.renderPage (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\build\index.js:156:34)
    at Build.render (C:\Users\farne\AppData\Roaming\npm\node_modules\vuepress\node_modules\@vuepress\core\lib\node\build\index.js:94:33)farne@DESKTOP-1CU9QC5 MINGW64 /u/Arquivos/Web/Web/2019/farnetani-blog-yubisaki (master)
````

**Comment by stickmy** [comment]
Any repo to reproduce?

**Comment by farnetani** [comment]
I solved! I think the problem was related to having deleted the package.lock and yarn.lock!
